<?xml version="1.0" encoding="utf-8"?><Database Name="hiscentral" Class="ObservationsMetadataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=kyle.ucsd.edu;Initial Catalog=hiscentral;Persist Security Info=True;User ID=hiscentraluser" SettingsObjectName="cuahsi.his.ogc.Properties.Settings" SettingsPropertyName="hiscentralConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.v_ObservationsDataTextGeom" Member="ObservationsSeriesMetadatas">
    <Type Name="ObservationsSeriesMetadata">
      <Column Name="ServCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SiteCode" Type="System.String" DbType="VarChar(101)" CanBeNull="true" />
      <Column Name="SiteName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="VarCode" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="VarName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="VarUnits" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Vocabulary" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Ontology" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="Concept" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Valuecount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Longitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IsRegular" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TimeUnits" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TimeStep" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DataType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Medium" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MethodID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Method" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="QCLevelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QCLevel" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SourceID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SourceName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LocType" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="ServType" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="XLL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="YLL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="XUR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="YUR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(357)" CanBeNull="true" />
      <Column Name="Variable" Type="System.String" DbType="NVarChar(356)" CanBeNull="true" />
      <Column Name="ReqsAuth" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WofVersion" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="WaterMLURI" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="WFSURI" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="WMSURI" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DAccessURI" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="StateName" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="Geometry" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RecordType" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="OrgHier" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SerStatus" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>