//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("hissandboxModel", "FK_Sites_SiteID", "Sites", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WCFServiceWebRole1.Site), "SeriesCatalog", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WCFServiceWebRole1.SeriesCatalog), true)]
[assembly: EdmRelationshipAttribute("hissandboxModel", "FK_Variables_VariableID", "Variables", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WCFServiceWebRole1.Variable), "SeriesCatalog", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WCFServiceWebRole1.SeriesCatalog), true)]

#endregion

namespace WCFServiceWebRole1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class hisEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new hisEntities object using the connection string found in the 'hisEntities' section of the application configuration file.
        /// </summary>
        public hisEntities() : base("name=hisEntities", "hisEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new hisEntities object.
        /// </summary>
        public hisEntities(string connectionString) : base(connectionString, "hisEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new hisEntities object.
        /// </summary>
        public hisEntities(EntityConnection connection) : base(connection, "hisEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SeriesCatalog> SeriesCatalogs
        {
            get
            {
                if ((_SeriesCatalogs == null))
                {
                    _SeriesCatalogs = base.CreateObjectSet<SeriesCatalog>("SeriesCatalogs");
                }
                return _SeriesCatalogs;
            }
        }
        private ObjectSet<SeriesCatalog> _SeriesCatalogs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Site> Sites
        {
            get
            {
                if ((_Sites == null))
                {
                    _Sites = base.CreateObjectSet<Site>("Sites");
                }
                return _Sites;
            }
        }
        private ObjectSet<Site> _Sites;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Variable> Variables
        {
            get
            {
                if ((_Variables == null))
                {
                    _Variables = base.CreateObjectSet<Variable>("Variables");
                }
                return _Variables;
            }
        }
        private ObjectSet<Variable> _Variables;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SeriesCatalogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSeriesCatalogs(SeriesCatalog seriesCatalog)
        {
            base.AddObject("SeriesCatalogs", seriesCatalog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sites EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSites(Site site)
        {
            base.AddObject("Sites", site);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Variables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVariables(Variable variable)
        {
            base.AddObject("Variables", variable);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hissandboxModel", Name="SeriesCatalog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SeriesCatalog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SeriesCatalog object.
        /// </summary>
        /// <param name="seriesID">Initial value of the SeriesID property.</param>
        /// <param name="siteID">Initial value of the SiteID property.</param>
        /// <param name="variableID">Initial value of the VariableID property.</param>
        /// <param name="beginDateTime">Initial value of the BeginDateTime property.</param>
        /// <param name="endDateTime">Initial value of the EndDateTime property.</param>
        /// <param name="valuecount">Initial value of the Valuecount property.</param>
        /// <param name="sourceID">Initial value of the SourceID property.</param>
        public static SeriesCatalog CreateSeriesCatalog(global::System.Int32 seriesID, global::System.Int32 siteID, global::System.Int32 variableID, global::System.DateTime beginDateTime, global::System.DateTime endDateTime, global::System.Int32 valuecount, global::System.Int32 sourceID)
        {
            SeriesCatalog seriesCatalog = new SeriesCatalog();
            seriesCatalog.SeriesID = seriesID;
            seriesCatalog.SiteID = siteID;
            seriesCatalog.VariableID = variableID;
            seriesCatalog.BeginDateTime = beginDateTime;
            seriesCatalog.EndDateTime = endDateTime;
            seriesCatalog.Valuecount = valuecount;
            seriesCatalog.SourceID = sourceID;
            return seriesCatalog;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SeriesID
        {
            get
            {
                return _SeriesID;
            }
            set
            {
                if (_SeriesID != value)
                {
                    OnSeriesIDChanging(value);
                    ReportPropertyChanging("SeriesID");
                    _SeriesID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SeriesID");
                    OnSeriesIDChanged();
                }
            }
        }
        private global::System.Int32 _SeriesID;
        partial void OnSeriesIDChanging(global::System.Int32 value);
        partial void OnSeriesIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SiteID
        {
            get
            {
                return _SiteID;
            }
            set
            {
                OnSiteIDChanging(value);
                ReportPropertyChanging("SiteID");
                _SiteID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SiteID");
                OnSiteIDChanged();
            }
        }
        private global::System.Int32 _SiteID;
        partial void OnSiteIDChanging(global::System.Int32 value);
        partial void OnSiteIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SiteCode
        {
            get
            {
                return _SiteCode;
            }
            set
            {
                OnSiteCodeChanging(value);
                ReportPropertyChanging("SiteCode");
                _SiteCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SiteCode");
                OnSiteCodeChanged();
            }
        }
        private global::System.String _SiteCode;
        partial void OnSiteCodeChanging(global::System.String value);
        partial void OnSiteCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SiteName
        {
            get
            {
                return _SiteName;
            }
            set
            {
                OnSiteNameChanging(value);
                ReportPropertyChanging("SiteName");
                _SiteName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SiteName");
                OnSiteNameChanged();
            }
        }
        private global::System.String _SiteName;
        partial void OnSiteNameChanging(global::System.String value);
        partial void OnSiteNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VariableID
        {
            get
            {
                return _VariableID;
            }
            set
            {
                OnVariableIDChanging(value);
                ReportPropertyChanging("VariableID");
                _VariableID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VariableID");
                OnVariableIDChanged();
            }
        }
        private global::System.Int32 _VariableID;
        partial void OnVariableIDChanging(global::System.Int32 value);
        partial void OnVariableIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VariableCodeSmall
        {
            get
            {
                return _VariableCodeSmall;
            }
            set
            {
                OnVariableCodeSmallChanging(value);
                ReportPropertyChanging("VariableCodeSmall");
                _VariableCodeSmall = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VariableCodeSmall");
                OnVariableCodeSmallChanged();
            }
        }
        private global::System.String _VariableCodeSmall;
        partial void OnVariableCodeSmallChanging(global::System.String value);
        partial void OnVariableCodeSmallChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VariableName
        {
            get
            {
                return _VariableName;
            }
            set
            {
                OnVariableNameChanging(value);
                ReportPropertyChanging("VariableName");
                _VariableName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VariableName");
                OnVariableNameChanged();
            }
        }
        private global::System.String _VariableName;
        partial void OnVariableNameChanging(global::System.String value);
        partial void OnVariableNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> VariableUnitsID
        {
            get
            {
                return _VariableUnitsID;
            }
            set
            {
                OnVariableUnitsIDChanging(value);
                ReportPropertyChanging("VariableUnitsID");
                _VariableUnitsID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VariableUnitsID");
                OnVariableUnitsIDChanged();
            }
        }
        private Nullable<global::System.Int32> _VariableUnitsID;
        partial void OnVariableUnitsIDChanging(Nullable<global::System.Int32> value);
        partial void OnVariableUnitsIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VariableUnitsName
        {
            get
            {
                return _VariableUnitsName;
            }
            set
            {
                OnVariableUnitsNameChanging(value);
                ReportPropertyChanging("VariableUnitsName");
                _VariableUnitsName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VariableUnitsName");
                OnVariableUnitsNameChanged();
            }
        }
        private global::System.String _VariableUnitsName;
        partial void OnVariableUnitsNameChanging(global::System.String value);
        partial void OnVariableUnitsNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SampleMedium
        {
            get
            {
                return _SampleMedium;
            }
            set
            {
                OnSampleMediumChanging(value);
                ReportPropertyChanging("SampleMedium");
                _SampleMedium = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SampleMedium");
                OnSampleMediumChanged();
            }
        }
        private global::System.String _SampleMedium;
        partial void OnSampleMediumChanging(global::System.String value);
        partial void OnSampleMediumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ValueType
        {
            get
            {
                return _ValueType;
            }
            set
            {
                OnValueTypeChanging(value);
                ReportPropertyChanging("ValueType");
                _ValueType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ValueType");
                OnValueTypeChanged();
            }
        }
        private global::System.String _ValueType;
        partial void OnValueTypeChanging(global::System.String value);
        partial void OnValueTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime BeginDateTime
        {
            get
            {
                return _BeginDateTime;
            }
            set
            {
                OnBeginDateTimeChanging(value);
                ReportPropertyChanging("BeginDateTime");
                _BeginDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BeginDateTime");
                OnBeginDateTimeChanged();
            }
        }
        private global::System.DateTime _BeginDateTime;
        partial void OnBeginDateTimeChanging(global::System.DateTime value);
        partial void OnBeginDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndDateTime
        {
            get
            {
                return _EndDateTime;
            }
            set
            {
                OnEndDateTimeChanging(value);
                ReportPropertyChanging("EndDateTime");
                _EndDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDateTime");
                OnEndDateTimeChanged();
            }
        }
        private global::System.DateTime _EndDateTime;
        partial void OnEndDateTimeChanging(global::System.DateTime value);
        partial void OnEndDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Valuecount
        {
            get
            {
                return _Valuecount;
            }
            set
            {
                OnValuecountChanging(value);
                ReportPropertyChanging("Valuecount");
                _Valuecount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Valuecount");
                OnValuecountChanged();
            }
        }
        private global::System.Int32 _Valuecount;
        partial void OnValuecountChanging(global::System.Int32 value);
        partial void OnValuecountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GeneralCategory
        {
            get
            {
                return _GeneralCategory;
            }
            set
            {
                OnGeneralCategoryChanging(value);
                ReportPropertyChanging("GeneralCategory");
                _GeneralCategory = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GeneralCategory");
                OnGeneralCategoryChanged();
            }
        }
        private Nullable<global::System.Int32> _GeneralCategory;
        partial void OnGeneralCategoryChanging(Nullable<global::System.Int32> value);
        partial void OnGeneralCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UTCOffset
        {
            get
            {
                return _UTCOffset;
            }
            set
            {
                OnUTCOffsetChanging(value);
                ReportPropertyChanging("UTCOffset");
                _UTCOffset = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UTCOffset");
                OnUTCOffsetChanged();
            }
        }
        private Nullable<global::System.Int32> _UTCOffset;
        partial void OnUTCOffsetChanging(Nullable<global::System.Int32> value);
        partial void OnUTCOffsetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SourceID
        {
            get
            {
                return _SourceID;
            }
            set
            {
                OnSourceIDChanging(value);
                ReportPropertyChanging("SourceID");
                _SourceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SourceID");
                OnSourceIDChanged();
            }
        }
        private global::System.Int32 _SourceID;
        partial void OnSourceIDChanging(global::System.Int32 value);
        partial void OnSourceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VariableCode
        {
            get
            {
                return _VariableCode;
            }
            set
            {
                OnVariableCodeChanging(value);
                ReportPropertyChanging("VariableCode");
                _VariableCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VariableCode");
                OnVariableCodeChanged();
            }
        }
        private global::System.String _VariableCode;
        partial void OnVariableCodeChanging(global::System.String value);
        partial void OnVariableCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SeriesCode
        {
            get
            {
                return _SeriesCode;
            }
            set
            {
                OnSeriesCodeChanging(value);
                ReportPropertyChanging("SeriesCode");
                _SeriesCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SeriesCode");
                OnSeriesCodeChanged();
            }
        }
        private global::System.String _SeriesCode;
        partial void OnSeriesCodeChanging(global::System.String value);
        partial void OnSeriesCodeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hissandboxModel", "FK_Sites_SiteID", "Sites")]
        public Site Site
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Site>("hissandboxModel.FK_Sites_SiteID", "Sites").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Site>("hissandboxModel.FK_Sites_SiteID", "Sites").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Site> SiteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Site>("hissandboxModel.FK_Sites_SiteID", "Sites");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Site>("hissandboxModel.FK_Sites_SiteID", "Sites", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hissandboxModel", "FK_Variables_VariableID", "Variables")]
        public Variable Variable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Variable>("hissandboxModel.FK_Variables_VariableID", "Variables").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Variable>("hissandboxModel.FK_Variables_VariableID", "Variables").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Variable> VariableReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Variable>("hissandboxModel.FK_Variables_VariableID", "Variables");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Variable>("hissandboxModel.FK_Variables_VariableID", "Variables", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hissandboxModel", Name="Site")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Site : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Site object.
        /// </summary>
        /// <param name="siteID">Initial value of the SiteID property.</param>
        /// <param name="siteCode">Initial value of the SiteCode property.</param>
        /// <param name="networkID">Initial value of the NetworkID property.</param>
        public static Site CreateSite(global::System.Int32 siteID, global::System.String siteCode, global::System.Int32 networkID)
        {
            Site site = new Site();
            site.SiteID = siteID;
            site.SiteCode = siteCode;
            site.NetworkID = networkID;
            return site;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SiteID
        {
            get
            {
                return _SiteID;
            }
            set
            {
                if (_SiteID != value)
                {
                    OnSiteIDChanging(value);
                    ReportPropertyChanging("SiteID");
                    _SiteID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SiteID");
                    OnSiteIDChanged();
                }
            }
        }
        private global::System.Int32 _SiteID;
        partial void OnSiteIDChanging(global::System.Int32 value);
        partial void OnSiteIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SiteCode
        {
            get
            {
                return _SiteCode;
            }
            set
            {
                OnSiteCodeChanging(value);
                ReportPropertyChanging("SiteCode");
                _SiteCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SiteCode");
                OnSiteCodeChanged();
            }
        }
        private global::System.String _SiteCode;
        partial void OnSiteCodeChanging(global::System.String value);
        partial void OnSiteCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SiteName
        {
            get
            {
                return _SiteName;
            }
            set
            {
                OnSiteNameChanging(value);
                ReportPropertyChanging("SiteName");
                _SiteName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SiteName");
                OnSiteNameChanged();
            }
        }
        private global::System.String _SiteName;
        partial void OnSiteNameChanging(global::System.String value);
        partial void OnSiteNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private Nullable<global::System.Double> _Latitude;
        partial void OnLatitudeChanging(Nullable<global::System.Double> value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private Nullable<global::System.Double> _Longitude;
        partial void OnLongitudeChanging(Nullable<global::System.Double> value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LatLongDatumID
        {
            get
            {
                return _LatLongDatumID;
            }
            set
            {
                OnLatLongDatumIDChanging(value);
                ReportPropertyChanging("LatLongDatumID");
                _LatLongDatumID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LatLongDatumID");
                OnLatLongDatumIDChanged();
            }
        }
        private global::System.String _LatLongDatumID;
        partial void OnLatLongDatumIDChanging(global::System.String value);
        partial void OnLatLongDatumIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> Elevation_m
        {
            get
            {
                return _Elevation_m;
            }
            set
            {
                OnElevation_mChanging(value);
                ReportPropertyChanging("Elevation_m");
                _Elevation_m = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Elevation_m");
                OnElevation_mChanged();
            }
        }
        private Nullable<global::System.Single> _Elevation_m;
        partial void OnElevation_mChanging(Nullable<global::System.Single> value);
        partial void OnElevation_mChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VerticalDatum
        {
            get
            {
                return _VerticalDatum;
            }
            set
            {
                OnVerticalDatumChanging(value);
                ReportPropertyChanging("VerticalDatum");
                _VerticalDatum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VerticalDatum");
                OnVerticalDatumChanged();
            }
        }
        private global::System.String _VerticalDatum;
        partial void OnVerticalDatumChanging(global::System.String value);
        partial void OnVerticalDatumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> LocalX
        {
            get
            {
                return _LocalX;
            }
            set
            {
                OnLocalXChanging(value);
                ReportPropertyChanging("LocalX");
                _LocalX = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LocalX");
                OnLocalXChanged();
            }
        }
        private Nullable<global::System.Double> _LocalX;
        partial void OnLocalXChanging(Nullable<global::System.Double> value);
        partial void OnLocalXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> LocalY
        {
            get
            {
                return _LocalY;
            }
            set
            {
                OnLocalYChanging(value);
                ReportPropertyChanging("LocalY");
                _LocalY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LocalY");
                OnLocalYChanged();
            }
        }
        private Nullable<global::System.Double> _LocalY;
        partial void OnLocalYChanging(Nullable<global::System.Double> value);
        partial void OnLocalYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LocalProjectionID
        {
            get
            {
                return _LocalProjectionID;
            }
            set
            {
                OnLocalProjectionIDChanging(value);
                ReportPropertyChanging("LocalProjectionID");
                _LocalProjectionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LocalProjectionID");
                OnLocalProjectionIDChanged();
            }
        }
        private Nullable<global::System.Int32> _LocalProjectionID;
        partial void OnLocalProjectionIDChanging(Nullable<global::System.Int32> value);
        partial void OnLocalProjectionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> PosAccuracy_m
        {
            get
            {
                return _PosAccuracy_m;
            }
            set
            {
                OnPosAccuracy_mChanging(value);
                ReportPropertyChanging("PosAccuracy_m");
                _PosAccuracy_m = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PosAccuracy_m");
                OnPosAccuracy_mChanged();
            }
        }
        private Nullable<global::System.Single> _PosAccuracy_m;
        partial void OnPosAccuracy_mChanging(Nullable<global::System.Single> value);
        partial void OnPosAccuracy_mChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StateName
        {
            get
            {
                return _StateName;
            }
            set
            {
                OnStateNameChanging(value);
                ReportPropertyChanging("StateName");
                _StateName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StateName");
                OnStateNameChanged();
            }
        }
        private global::System.String _StateName;
        partial void OnStateNameChanging(global::System.String value);
        partial void OnStateNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String County
        {
            get
            {
                return _County;
            }
            set
            {
                OnCountyChanging(value);
                ReportPropertyChanging("County");
                _County = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("County");
                OnCountyChanged();
            }
        }
        private global::System.String _County;
        partial void OnCountyChanging(global::System.String value);
        partial void OnCountyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comments
        {
            get
            {
                return _Comments;
            }
            set
            {
                OnCommentsChanging(value);
                ReportPropertyChanging("Comments");
                _Comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comments");
                OnCommentsChanged();
            }
        }
        private global::System.String _Comments;
        partial void OnCommentsChanging(global::System.String value);
        partial void OnCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OrganizationName
        {
            get
            {
                return _OrganizationName;
            }
            set
            {
                OnOrganizationNameChanging(value);
                ReportPropertyChanging("OrganizationName");
                _OrganizationName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OrganizationName");
                OnOrganizationNameChanged();
            }
        }
        private global::System.String _OrganizationName;
        partial void OnOrganizationNameChanging(global::System.String value);
        partial void OnOrganizationNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HUC
        {
            get
            {
                return _HUC;
            }
            set
            {
                OnHUCChanging(value);
                ReportPropertyChanging("HUC");
                _HUC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HUC");
                OnHUCChanged();
            }
        }
        private global::System.String _HUC;
        partial void OnHUCChanging(global::System.String value);
        partial void OnHUCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> HUCnumeric
        {
            get
            {
                return _HUCnumeric;
            }
            set
            {
                OnHUCnumericChanging(value);
                ReportPropertyChanging("HUCnumeric");
                _HUCnumeric = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HUCnumeric");
                OnHUCnumericChanged();
            }
        }
        private Nullable<global::System.Decimal> _HUCnumeric;
        partial void OnHUCnumericChanging(Nullable<global::System.Decimal> value);
        partial void OnHUCnumericChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NetworkID
        {
            get
            {
                return _NetworkID;
            }
            set
            {
                OnNetworkIDChanging(value);
                ReportPropertyChanging("NetworkID");
                _NetworkID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NetworkID");
                OnNetworkIDChanged();
            }
        }
        private global::System.Int32 _NetworkID;
        partial void OnNetworkIDChanging(global::System.Int32 value);
        partial void OnNetworkIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hissandboxModel", "FK_Sites_SiteID", "SeriesCatalog")]
        public EntityCollection<SeriesCatalog> SeriesCatalogs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SeriesCatalog>("hissandboxModel.FK_Sites_SiteID", "SeriesCatalog");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SeriesCatalog>("hissandboxModel.FK_Sites_SiteID", "SeriesCatalog", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hissandboxModel", Name="Variable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Variable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Variable object.
        /// </summary>
        /// <param name="variableID">Initial value of the VariableID property.</param>
        public static Variable CreateVariable(global::System.Int32 variableID)
        {
            Variable variable = new Variable();
            variable.VariableID = variableID;
            return variable;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VariableID
        {
            get
            {
                return _VariableID;
            }
            set
            {
                if (_VariableID != value)
                {
                    OnVariableIDChanging(value);
                    ReportPropertyChanging("VariableID");
                    _VariableID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VariableID");
                    OnVariableIDChanged();
                }
            }
        }
        private global::System.Int32 _VariableID;
        partial void OnVariableIDChanging(global::System.Int32 value);
        partial void OnVariableIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Variable1
        {
            get
            {
                return _Variable1;
            }
            set
            {
                OnVariable1Changing(value);
                ReportPropertyChanging("Variable1");
                _Variable1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Variable1");
                OnVariable1Changed();
            }
        }
        private global::System.String _Variable1;
        partial void OnVariable1Changing(global::System.String value);
        partial void OnVariable1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UnitID
        {
            get
            {
                return _UnitID;
            }
            set
            {
                OnUnitIDChanging(value);
                ReportPropertyChanging("UnitID");
                _UnitID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitID");
                OnUnitIDChanged();
            }
        }
        private Nullable<global::System.Int32> _UnitID;
        partial void OnUnitIDChanging(Nullable<global::System.Int32> value);
        partial void OnUnitIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SampleMedium
        {
            get
            {
                return _SampleMedium;
            }
            set
            {
                OnSampleMediumChanging(value);
                ReportPropertyChanging("SampleMedium");
                _SampleMedium = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SampleMedium");
                OnSampleMediumChanged();
            }
        }
        private global::System.String _SampleMedium;
        partial void OnSampleMediumChanging(global::System.String value);
        partial void OnSampleMediumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ValueType
        {
            get
            {
                return _ValueType;
            }
            set
            {
                OnValueTypeChanging(value);
                ReportPropertyChanging("ValueType");
                _ValueType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ValueType");
                OnValueTypeChanged();
            }
        }
        private global::System.String _ValueType;
        partial void OnValueTypeChanging(global::System.String value);
        partial void OnValueTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsRegular
        {
            get
            {
                return _IsRegular;
            }
            set
            {
                OnIsRegularChanging(value);
                ReportPropertyChanging("IsRegular");
                _IsRegular = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsRegular");
                OnIsRegularChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsRegular;
        partial void OnIsRegularChanging(Nullable<global::System.Boolean> value);
        partial void OnIsRegularChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TimeSupport
        {
            get
            {
                return _TimeSupport;
            }
            set
            {
                OnTimeSupportChanging(value);
                ReportPropertyChanging("TimeSupport");
                _TimeSupport = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeSupport");
                OnTimeSupportChanged();
            }
        }
        private Nullable<global::System.Int32> _TimeSupport;
        partial void OnTimeSupportChanging(Nullable<global::System.Int32> value);
        partial void OnTimeSupportChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TimeUnitID
        {
            get
            {
                return _TimeUnitID;
            }
            set
            {
                OnTimeUnitIDChanging(value);
                ReportPropertyChanging("TimeUnitID");
                _TimeUnitID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeUnitID");
                OnTimeUnitIDChanged();
            }
        }
        private Nullable<global::System.Int32> _TimeUnitID;
        partial void OnTimeUnitIDChanging(Nullable<global::System.Int32> value);
        partial void OnTimeUnitIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DataType
        {
            get
            {
                return _DataType;
            }
            set
            {
                OnDataTypeChanging(value);
                ReportPropertyChanging("DataType");
                _DataType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DataType");
                OnDataTypeChanged();
            }
        }
        private global::System.String _DataType;
        partial void OnDataTypeChanging(global::System.String value);
        partial void OnDataTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GeneralCategory
        {
            get
            {
                return _GeneralCategory;
            }
            set
            {
                OnGeneralCategoryChanging(value);
                ReportPropertyChanging("GeneralCategory");
                _GeneralCategory = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GeneralCategory");
                OnGeneralCategoryChanged();
            }
        }
        private global::System.String _GeneralCategory;
        partial void OnGeneralCategoryChanging(global::System.String value);
        partial void OnGeneralCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AltVariableCode
        {
            get
            {
                return _AltVariableCode;
            }
            set
            {
                OnAltVariableCodeChanging(value);
                ReportPropertyChanging("AltVariableCode");
                _AltVariableCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AltVariableCode");
                OnAltVariableCodeChanged();
            }
        }
        private global::System.String _AltVariableCode;
        partial void OnAltVariableCodeChanging(global::System.String value);
        partial void OnAltVariableCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AltVariableName
        {
            get
            {
                return _AltVariableName;
            }
            set
            {
                OnAltVariableNameChanging(value);
                ReportPropertyChanging("AltVariableName");
                _AltVariableName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AltVariableName");
                OnAltVariableNameChanged();
            }
        }
        private global::System.String _AltVariableName;
        partial void OnAltVariableNameChanging(global::System.String value);
        partial void OnAltVariableNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AltUnits
        {
            get
            {
                return _AltUnits;
            }
            set
            {
                OnAltUnitsChanging(value);
                ReportPropertyChanging("AltUnits");
                _AltUnits = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AltUnits");
                OnAltUnitsChanged();
            }
        }
        private global::System.String _AltUnits;
        partial void OnAltUnitsChanging(global::System.String value);
        partial void OnAltUnitsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> networkId
        {
            get
            {
                return _networkId;
            }
            set
            {
                OnnetworkIdChanging(value);
                ReportPropertyChanging("networkId");
                _networkId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("networkId");
                OnnetworkIdChanged();
            }
        }
        private Nullable<global::System.Int32> _networkId;
        partial void OnnetworkIdChanging(Nullable<global::System.Int32> value);
        partial void OnnetworkIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hissandboxModel", "FK_Variables_VariableID", "SeriesCatalog")]
        public EntityCollection<SeriesCatalog> SeriesCatalogs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SeriesCatalog>("hissandboxModel.FK_Variables_VariableID", "SeriesCatalog");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SeriesCatalog>("hissandboxModel.FK_Variables_VariableID", "SeriesCatalog", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
