#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace genericws.example
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LittleBear11")]
	public partial class SitesSeriesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertVariable(GenericWebservice.Variable instance);
    partial void UpdateVariable(GenericWebservice.Variable instance);
    partial void DeleteVariable(GenericWebservice.Variable instance);
    partial void InsertSeriesCatalog(GenericWebservice.SeriesCatalog instance);
    partial void UpdateSeriesCatalog(GenericWebservice.SeriesCatalog instance);
    partial void DeleteSeriesCatalog(GenericWebservice.SeriesCatalog instance);
    partial void InsertSite(GenericWebservice.Site instance);
    partial void UpdateSite(GenericWebservice.Site instance);
    partial void DeleteSite(GenericWebservice.Site instance);
    #endregion
		
		public SitesSeriesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ODDB"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SitesSeriesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SitesSeriesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SitesSeriesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SitesSeriesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}

        public System.Data.Linq.Table<GenericWebservice.Variable> Variables
		{
			get
			{
				return this.GetTable<GenericWebservice.Variable>();
			}
		}

        public System.Data.Linq.Table<GenericWebservice.SeriesCatalog> SeriesCatalogs
		{
			get
			{
                return this.GetTable<GenericWebservice.SeriesCatalog>();
			}
		}

        public System.Data.Linq.Table<GenericWebservice.Site> Sites
		{
			get
			{
				return this.GetTable<GenericWebservice.Site>();
			}
		}
	}
}
namespace GenericWebservice
{
	using System.Runtime.Serialization;
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Variables")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Variable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _VariableID;
		
		private string _VariableCode;
		
		private string _VariableName;
		
		private string _Speciation;
		
		private int _VariableUnitsID;
		
		private string _SampleMedium;
		
		private string _ValueType;
		
		private bool _IsRegular;
		
		private double _TimeSupport;
		
		private int _TimeUnitsID;
		
		private string _DataType;
		
		private string _GeneralCategory;
		
		private double _NoDataValue;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVariableIDChanging(int value);
    partial void OnVariableIDChanged();
    partial void OnVariableCodeChanging(string value);
    partial void OnVariableCodeChanged();
    partial void OnVariableNameChanging(string value);
    partial void OnVariableNameChanged();
    partial void OnSpeciationChanging(string value);
    partial void OnSpeciationChanged();
    partial void OnVariableUnitsIDChanging(int value);
    partial void OnVariableUnitsIDChanged();
    partial void OnSampleMediumChanging(string value);
    partial void OnSampleMediumChanged();
    partial void OnValueTypeChanging(string value);
    partial void OnValueTypeChanged();
    partial void OnIsRegularChanging(bool value);
    partial void OnIsRegularChanged();
    partial void OnTimeSupportChanging(double value);
    partial void OnTimeSupportChanged();
    partial void OnTimeUnitsIDChanging(int value);
    partial void OnTimeUnitsIDChanged();
    partial void OnDataTypeChanging(string value);
    partial void OnDataTypeChanged();
    partial void OnGeneralCategoryChanging(string value);
    partial void OnGeneralCategoryChanged();
    partial void OnNoDataValueChanging(double value);
    partial void OnNoDataValueChanged();
    #endregion
		
		public Variable()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VariableID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int VariableID
		{
			get
			{
				return this._VariableID;
			}
			set
			{
				if ((this._VariableID != value))
				{
					this.OnVariableIDChanging(value);
					this.SendPropertyChanging();
					this._VariableID = value;
					this.SendPropertyChanged("VariableID");
					this.OnVariableIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VariableCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string VariableCode
		{
			get
			{
				return this._VariableCode;
			}
			set
			{
				if ((this._VariableCode != value))
				{
					this.OnVariableCodeChanging(value);
					this.SendPropertyChanging();
					this._VariableCode = value;
					this.SendPropertyChanged("VariableCode");
					this.OnVariableCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VariableName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string VariableName
		{
			get
			{
				return this._VariableName;
			}
			set
			{
				if ((this._VariableName != value))
				{
					this.OnVariableNameChanging(value);
					this.SendPropertyChanging();
					this._VariableName = value;
					this.SendPropertyChanged("VariableName");
					this.OnVariableNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Speciation", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string Speciation
		{
			get
			{
				return this._Speciation;
			}
			set
			{
				if ((this._Speciation != value))
				{
					this.OnSpeciationChanging(value);
					this.SendPropertyChanging();
					this._Speciation = value;
					this.SendPropertyChanged("Speciation");
					this.OnSpeciationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VariableUnitsID", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public int VariableUnitsID
		{
			get
			{
				return this._VariableUnitsID;
			}
			set
			{
				if ((this._VariableUnitsID != value))
				{
					this.OnVariableUnitsIDChanging(value);
					this.SendPropertyChanging();
					this._VariableUnitsID = value;
					this.SendPropertyChanged("VariableUnitsID");
					this.OnVariableUnitsIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SampleMedium", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string SampleMedium
		{
			get
			{
				return this._SampleMedium;
			}
			set
			{
				if ((this._SampleMedium != value))
				{
					this.OnSampleMediumChanging(value);
					this.SendPropertyChanging();
					this._SampleMedium = value;
					this.SendPropertyChanged("SampleMedium");
					this.OnSampleMediumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValueType", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string ValueType
		{
			get
			{
				return this._ValueType;
			}
			set
			{
				if ((this._ValueType != value))
				{
					this.OnValueTypeChanging(value);
					this.SendPropertyChanging();
					this._ValueType = value;
					this.SendPropertyChanged("ValueType");
					this.OnValueTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRegular", DbType="Bit NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public bool IsRegular
		{
			get
			{
				return this._IsRegular;
			}
			set
			{
				if ((this._IsRegular != value))
				{
					this.OnIsRegularChanging(value);
					this.SendPropertyChanging();
					this._IsRegular = value;
					this.SendPropertyChanged("IsRegular");
					this.OnIsRegularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeSupport", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public double TimeSupport
		{
			get
			{
				return this._TimeSupport;
			}
			set
			{
				if ((this._TimeSupport != value))
				{
					this.OnTimeSupportChanging(value);
					this.SendPropertyChanging();
					this._TimeSupport = value;
					this.SendPropertyChanged("TimeSupport");
					this.OnTimeSupportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeUnitsID", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public int TimeUnitsID
		{
			get
			{
				return this._TimeUnitsID;
			}
			set
			{
				if ((this._TimeUnitsID != value))
				{
					this.OnTimeUnitsIDChanging(value);
					this.SendPropertyChanging();
					this._TimeUnitsID = value;
					this.SendPropertyChanged("TimeUnitsID");
					this.OnTimeUnitsIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataType", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public string DataType
		{
			get
			{
				return this._DataType;
			}
			set
			{
				if ((this._DataType != value))
				{
					this.OnDataTypeChanging(value);
					this.SendPropertyChanging();
					this._DataType = value;
					this.SendPropertyChanged("DataType");
					this.OnDataTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GeneralCategory", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public string GeneralCategory
		{
			get
			{
				return this._GeneralCategory;
			}
			set
			{
				if ((this._GeneralCategory != value))
				{
					this.OnGeneralCategoryChanging(value);
					this.SendPropertyChanging();
					this._GeneralCategory = value;
					this.SendPropertyChanged("GeneralCategory");
					this.OnGeneralCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoDataValue", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public double NoDataValue
		{
			get
			{
				return this._NoDataValue;
			}
			set
			{
				if ((this._NoDataValue != value))
				{
					this.OnNoDataValueChanging(value);
					this.SendPropertyChanging();
					this._NoDataValue = value;
					this.SendPropertyChanged("NoDataValue");
					this.OnNoDataValueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SeriesCatalog")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class SeriesCatalog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SeriesID;
		
		private System.Nullable<int> _SiteID;
		
		private string _SiteCode;
		
		private string _SiteName;
		
		private System.Nullable<int> _VariableID;
		
		private string _VariableCode;
		
		private string _VariableName;
		
		private string _Speciation;
		
		private System.Nullable<int> _VariableUnitsID;
		
		private string _VariableUnitsName;
		
		private string _SampleMedium;
		
		private string _ValueType;
		
		private System.Nullable<double> _TimeSupport;
		
		private System.Nullable<int> _TimeUnitsID;
		
		private string _TimeUnitsName;
		
		private string _DataType;
		
		private string _GeneralCategory;
		
		private System.Nullable<int> _MethodID;
		
		private string _MethodDescription;
		
		private System.Nullable<int> _SourceID;
		
		private string _Organization;
		
		private string _SourceDescription;
		
		private string _Citation;
		
		private System.Nullable<int> _QualityControlLevelID;
		
		private string _QualityControlLevelCode;
		
		private System.Nullable<System.DateTimeOffset> _BeginDateTime;
		
		private System.Nullable<System.DateTimeOffset> _EndDateTime;
		
		private System.Nullable<System.DateTimeOffset> _BeginDateTimeUTC;
		
		private System.Nullable<System.DateTimeOffset> _EndDateTimeUTC;
		
		private System.Nullable<int> _ValueCount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSeriesIDChanging(int value);
    partial void OnSeriesIDChanged();
    partial void OnSiteIDChanging(System.Nullable<int> value);
    partial void OnSiteIDChanged();
    partial void OnSiteCodeChanging(string value);
    partial void OnSiteCodeChanged();
    partial void OnSiteNameChanging(string value);
    partial void OnSiteNameChanged();
    partial void OnVariableIDChanging(System.Nullable<int> value);
    partial void OnVariableIDChanged();
    partial void OnVariableCodeChanging(string value);
    partial void OnVariableCodeChanged();
    partial void OnVariableNameChanging(string value);
    partial void OnVariableNameChanged();
    partial void OnSpeciationChanging(string value);
    partial void OnSpeciationChanged();
    partial void OnVariableUnitsIDChanging(System.Nullable<int> value);
    partial void OnVariableUnitsIDChanged();
    partial void OnVariableUnitsNameChanging(string value);
    partial void OnVariableUnitsNameChanged();
    partial void OnSampleMediumChanging(string value);
    partial void OnSampleMediumChanged();
    partial void OnValueTypeChanging(string value);
    partial void OnValueTypeChanged();
    partial void OnTimeSupportChanging(System.Nullable<double> value);
    partial void OnTimeSupportChanged();
    partial void OnTimeUnitsIDChanging(System.Nullable<int> value);
    partial void OnTimeUnitsIDChanged();
    partial void OnTimeUnitsNameChanging(string value);
    partial void OnTimeUnitsNameChanged();
    partial void OnDataTypeChanging(string value);
    partial void OnDataTypeChanged();
    partial void OnGeneralCategoryChanging(string value);
    partial void OnGeneralCategoryChanged();
    partial void OnMethodIDChanging(System.Nullable<int> value);
    partial void OnMethodIDChanged();
    partial void OnMethodDescriptionChanging(string value);
    partial void OnMethodDescriptionChanged();
    partial void OnSourceIDChanging(System.Nullable<int> value);
    partial void OnSourceIDChanged();
    partial void OnOrganizationChanging(string value);
    partial void OnOrganizationChanged();
    partial void OnSourceDescriptionChanging(string value);
    partial void OnSourceDescriptionChanged();
    partial void OnCitationChanging(string value);
    partial void OnCitationChanged();
    partial void OnQualityControlLevelIDChanging(System.Nullable<int> value);
    partial void OnQualityControlLevelIDChanged();
    partial void OnQualityControlLevelCodeChanging(string value);
    partial void OnQualityControlLevelCodeChanged();
    partial void OnBeginDateTimeChanging(System.Nullable<System.DateTimeOffset> value);
    partial void OnBeginDateTimeChanged();
    partial void OnEndDateTimeChanging(System.Nullable<System.DateTimeOffset> value);
    partial void OnEndDateTimeChanged();
    partial void OnBeginDateTimeUTCChanging(System.Nullable<System.DateTimeOffset> value);
    partial void OnBeginDateTimeUTCChanged();
    partial void OnEndDateTimeUTCChanging(System.Nullable<System.DateTimeOffset> value);
    partial void OnEndDateTimeUTCChanged();
    partial void OnValueCountChanging(System.Nullable<int> value);
    partial void OnValueCountChanged();
    #endregion
		
		public SeriesCatalog()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeriesID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int SeriesID
		{
			get
			{
				return this._SeriesID;
			}
			set
			{
				if ((this._SeriesID != value))
				{
					this.OnSeriesIDChanging(value);
					this.SendPropertyChanging();
					this._SeriesID = value;
					this.SendPropertyChanged("SeriesID");
					this.OnSeriesIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.Nullable<int> SiteID
		{
			get
			{
				return this._SiteID;
			}
			set
			{
				if ((this._SiteID != value))
				{
					this.OnSiteIDChanging(value);
					this.SendPropertyChanging();
					this._SiteID = value;
					this.SendPropertyChanged("SiteID");
					this.OnSiteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteCode", DbType="NVarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string SiteCode
		{
			get
			{
				return this._SiteCode;
			}
			set
			{
				if ((this._SiteCode != value))
				{
					this.OnSiteCodeChanging(value);
					this.SendPropertyChanging();
					this._SiteCode = value;
					this.SendPropertyChanged("SiteCode");
					this.OnSiteCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteName", DbType="NVarChar(255)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string SiteName
		{
			get
			{
				return this._SiteName;
			}
			set
			{
				if ((this._SiteName != value))
				{
					this.OnSiteNameChanging(value);
					this.SendPropertyChanging();
					this._SiteName = value;
					this.SendPropertyChanged("SiteName");
					this.OnSiteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VariableID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<int> VariableID
		{
			get
			{
				return this._VariableID;
			}
			set
			{
				if ((this._VariableID != value))
				{
					this.OnVariableIDChanging(value);
					this.SendPropertyChanging();
					this._VariableID = value;
					this.SendPropertyChanged("VariableID");
					this.OnVariableIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VariableCode", DbType="NVarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string VariableCode
		{
			get
			{
				return this._VariableCode;
			}
			set
			{
				if ((this._VariableCode != value))
				{
					this.OnVariableCodeChanging(value);
					this.SendPropertyChanging();
					this._VariableCode = value;
					this.SendPropertyChanged("VariableCode");
					this.OnVariableCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VariableName", DbType="NVarChar(255)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string VariableName
		{
			get
			{
				return this._VariableName;
			}
			set
			{
				if ((this._VariableName != value))
				{
					this.OnVariableNameChanging(value);
					this.SendPropertyChanging();
					this._VariableName = value;
					this.SendPropertyChanged("VariableName");
					this.OnVariableNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Speciation", DbType="NVarChar(255)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string Speciation
		{
			get
			{
				return this._Speciation;
			}
			set
			{
				if ((this._Speciation != value))
				{
					this.OnSpeciationChanging(value);
					this.SendPropertyChanging();
					this._Speciation = value;
					this.SendPropertyChanged("Speciation");
					this.OnSpeciationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VariableUnitsID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public System.Nullable<int> VariableUnitsID
		{
			get
			{
				return this._VariableUnitsID;
			}
			set
			{
				if ((this._VariableUnitsID != value))
				{
					this.OnVariableUnitsIDChanging(value);
					this.SendPropertyChanging();
					this._VariableUnitsID = value;
					this.SendPropertyChanged("VariableUnitsID");
					this.OnVariableUnitsIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VariableUnitsName", DbType="NVarChar(255)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public string VariableUnitsName
		{
			get
			{
				return this._VariableUnitsName;
			}
			set
			{
				if ((this._VariableUnitsName != value))
				{
					this.OnVariableUnitsNameChanging(value);
					this.SendPropertyChanging();
					this._VariableUnitsName = value;
					this.SendPropertyChanged("VariableUnitsName");
					this.OnVariableUnitsNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SampleMedium", DbType="NVarChar(255)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public string SampleMedium
		{
			get
			{
				return this._SampleMedium;
			}
			set
			{
				if ((this._SampleMedium != value))
				{
					this.OnSampleMediumChanging(value);
					this.SendPropertyChanging();
					this._SampleMedium = value;
					this.SendPropertyChanged("SampleMedium");
					this.OnSampleMediumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValueType", DbType="NVarChar(255)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public string ValueType
		{
			get
			{
				return this._ValueType;
			}
			set
			{
				if ((this._ValueType != value))
				{
					this.OnValueTypeChanging(value);
					this.SendPropertyChanging();
					this._ValueType = value;
					this.SendPropertyChanged("ValueType");
					this.OnValueTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeSupport", DbType="Float")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public System.Nullable<double> TimeSupport
		{
			get
			{
				return this._TimeSupport;
			}
			set
			{
				if ((this._TimeSupport != value))
				{
					this.OnTimeSupportChanging(value);
					this.SendPropertyChanging();
					this._TimeSupport = value;
					this.SendPropertyChanged("TimeSupport");
					this.OnTimeSupportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeUnitsID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public System.Nullable<int> TimeUnitsID
		{
			get
			{
				return this._TimeUnitsID;
			}
			set
			{
				if ((this._TimeUnitsID != value))
				{
					this.OnTimeUnitsIDChanging(value);
					this.SendPropertyChanging();
					this._TimeUnitsID = value;
					this.SendPropertyChanged("TimeUnitsID");
					this.OnTimeUnitsIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeUnitsName", DbType="NVarChar(255)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public string TimeUnitsName
		{
			get
			{
				return this._TimeUnitsName;
			}
			set
			{
				if ((this._TimeUnitsName != value))
				{
					this.OnTimeUnitsNameChanging(value);
					this.SendPropertyChanging();
					this._TimeUnitsName = value;
					this.SendPropertyChanged("TimeUnitsName");
					this.OnTimeUnitsNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataType", DbType="NVarChar(255)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=16)]
		public string DataType
		{
			get
			{
				return this._DataType;
			}
			set
			{
				if ((this._DataType != value))
				{
					this.OnDataTypeChanging(value);
					this.SendPropertyChanging();
					this._DataType = value;
					this.SendPropertyChanged("DataType");
					this.OnDataTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GeneralCategory", DbType="NVarChar(255)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=17)]
		public string GeneralCategory
		{
			get
			{
				return this._GeneralCategory;
			}
			set
			{
				if ((this._GeneralCategory != value))
				{
					this.OnGeneralCategoryChanging(value);
					this.SendPropertyChanging();
					this._GeneralCategory = value;
					this.SendPropertyChanged("GeneralCategory");
					this.OnGeneralCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MethodID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=18)]
		public System.Nullable<int> MethodID
		{
			get
			{
				return this._MethodID;
			}
			set
			{
				if ((this._MethodID != value))
				{
					this.OnMethodIDChanging(value);
					this.SendPropertyChanging();
					this._MethodID = value;
					this.SendPropertyChanged("MethodID");
					this.OnMethodIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MethodDescription", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=19)]
		public string MethodDescription
		{
			get
			{
				return this._MethodDescription;
			}
			set
			{
				if ((this._MethodDescription != value))
				{
					this.OnMethodDescriptionChanging(value);
					this.SendPropertyChanging();
					this._MethodDescription = value;
					this.SendPropertyChanged("MethodDescription");
					this.OnMethodDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=20)]
		public System.Nullable<int> SourceID
		{
			get
			{
				return this._SourceID;
			}
			set
			{
				if ((this._SourceID != value))
				{
					this.OnSourceIDChanging(value);
					this.SendPropertyChanging();
					this._SourceID = value;
					this.SendPropertyChanged("SourceID");
					this.OnSourceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Organization", DbType="NVarChar(255)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=21)]
		public string Organization
		{
			get
			{
				return this._Organization;
			}
			set
			{
				if ((this._Organization != value))
				{
					this.OnOrganizationChanging(value);
					this.SendPropertyChanging();
					this._Organization = value;
					this.SendPropertyChanged("Organization");
					this.OnOrganizationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceDescription", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=22)]
		public string SourceDescription
		{
			get
			{
				return this._SourceDescription;
			}
			set
			{
				if ((this._SourceDescription != value))
				{
					this.OnSourceDescriptionChanging(value);
					this.SendPropertyChanging();
					this._SourceDescription = value;
					this.SendPropertyChanged("SourceDescription");
					this.OnSourceDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Citation", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=23)]
		public string Citation
		{
			get
			{
				return this._Citation;
			}
			set
			{
				if ((this._Citation != value))
				{
					this.OnCitationChanging(value);
					this.SendPropertyChanging();
					this._Citation = value;
					this.SendPropertyChanged("Citation");
					this.OnCitationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QualityControlLevelID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=24)]
		public System.Nullable<int> QualityControlLevelID
		{
			get
			{
				return this._QualityControlLevelID;
			}
			set
			{
				if ((this._QualityControlLevelID != value))
				{
					this.OnQualityControlLevelIDChanging(value);
					this.SendPropertyChanging();
					this._QualityControlLevelID = value;
					this.SendPropertyChanged("QualityControlLevelID");
					this.OnQualityControlLevelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QualityControlLevelCode", DbType="NVarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=25)]
		public string QualityControlLevelCode
		{
			get
			{
				return this._QualityControlLevelCode;
			}
			set
			{
				if ((this._QualityControlLevelCode != value))
				{
					this.OnQualityControlLevelCodeChanging(value);
					this.SendPropertyChanging();
					this._QualityControlLevelCode = value;
					this.SendPropertyChanged("QualityControlLevelCode");
					this.OnQualityControlLevelCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeginDateTime", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=26)]
		public System.Nullable<System.DateTimeOffset> BeginDateTime
		{
			get
			{
				return this._BeginDateTime;
			}
			set
			{
				if ((this._BeginDateTime != value))
				{
					this.OnBeginDateTimeChanging(value);
					this.SendPropertyChanging();
					this._BeginDateTime = value;
					this.SendPropertyChanged("BeginDateTime");
					this.OnBeginDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDateTime", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=27)]
		public System.Nullable<System.DateTimeOffset> EndDateTime
		{
			get
			{
				return this._EndDateTime;
			}
			set
			{
				if ((this._EndDateTime != value))
				{
					this.OnEndDateTimeChanging(value);
					this.SendPropertyChanging();
					this._EndDateTime = value;
					this.SendPropertyChanged("EndDateTime");
					this.OnEndDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeginDateTimeUTC", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=28)]
		public System.Nullable<System.DateTimeOffset> BeginDateTimeUTC
		{
			get
			{
				return this._BeginDateTimeUTC;
			}
			set
			{
				if ((this._BeginDateTimeUTC != value))
				{
					this.OnBeginDateTimeUTCChanging(value);
					this.SendPropertyChanging();
					this._BeginDateTimeUTC = value;
					this.SendPropertyChanged("BeginDateTimeUTC");
					this.OnBeginDateTimeUTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDateTimeUTC", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=29)]
		public System.Nullable<System.DateTimeOffset> EndDateTimeUTC
		{
			get
			{
				return this._EndDateTimeUTC;
			}
			set
			{
				if ((this._EndDateTimeUTC != value))
				{
					this.OnEndDateTimeUTCChanging(value);
					this.SendPropertyChanging();
					this._EndDateTimeUTC = value;
					this.SendPropertyChanged("EndDateTimeUTC");
					this.OnEndDateTimeUTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValueCount", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=30)]
		public System.Nullable<int> ValueCount
		{
			get
			{
				return this._ValueCount;
			}
			set
			{
				if ((this._ValueCount != value))
				{
					this.OnValueCountChanging(value);
					this.SendPropertyChanging();
					this._ValueCount = value;
					this.SendPropertyChanged("ValueCount");
					this.OnValueCountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sites")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Site : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SiteID;
		
		private string _SiteCode;
		
		private string _SiteName;
		
		private double _Latitude;
		
		private double _Longitude;
		
		private int _LatLongDatumID;
		
		private System.Nullable<double> _Elevation_m;
		
		private string _VerticalDatum;
		
		private System.Nullable<double> _LocalX;
		
		private System.Nullable<double> _LocalY;
		
		private System.Nullable<int> _LocalProjectionID;
		
		private System.Nullable<double> _PosAccuracy_m;
		
		private string _State;
		
		private string _County;
		
		private string _Comments;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSiteIDChanging(int value);
    partial void OnSiteIDChanged();
    partial void OnSiteCodeChanging(string value);
    partial void OnSiteCodeChanged();
    partial void OnSiteNameChanging(string value);
    partial void OnSiteNameChanged();
    partial void OnLatitudeChanging(double value);
    partial void OnLatitudeChanged();
    partial void OnLongitudeChanging(double value);
    partial void OnLongitudeChanged();
    partial void OnLatLongDatumIDChanging(int value);
    partial void OnLatLongDatumIDChanged();
    partial void OnElevation_mChanging(System.Nullable<double> value);
    partial void OnElevation_mChanged();
    partial void OnVerticalDatumChanging(string value);
    partial void OnVerticalDatumChanged();
    partial void OnLocalXChanging(System.Nullable<double> value);
    partial void OnLocalXChanged();
    partial void OnLocalYChanging(System.Nullable<double> value);
    partial void OnLocalYChanged();
    partial void OnLocalProjectionIDChanging(System.Nullable<int> value);
    partial void OnLocalProjectionIDChanged();
    partial void OnPosAccuracy_mChanging(System.Nullable<double> value);
    partial void OnPosAccuracy_mChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnCountyChanging(string value);
    partial void OnCountyChanged();
    partial void OnCommentsChanging(string value);
    partial void OnCommentsChanged();
    #endregion
		
		public Site()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int SiteID
		{
			get
			{
				return this._SiteID;
			}
			set
			{
				if ((this._SiteID != value))
				{
					this.OnSiteIDChanging(value);
					this.SendPropertyChanging();
					this._SiteID = value;
					this.SendPropertyChanged("SiteID");
					this.OnSiteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string SiteCode
		{
			get
			{
				return this._SiteCode;
			}
			set
			{
				if ((this._SiteCode != value))
				{
					this.OnSiteCodeChanging(value);
					this.SendPropertyChanging();
					this._SiteCode = value;
					this.SendPropertyChanged("SiteCode");
					this.OnSiteCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string SiteName
		{
			get
			{
				return this._SiteName;
			}
			set
			{
				if ((this._SiteName != value))
				{
					this.OnSiteNameChanging(value);
					this.SendPropertyChanging();
					this._SiteName = value;
					this.SendPropertyChanged("SiteName");
					this.OnSiteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public double Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this.OnLatitudeChanging(value);
					this.SendPropertyChanging();
					this._Latitude = value;
					this.SendPropertyChanged("Latitude");
					this.OnLatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Float NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public double Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this.OnLongitudeChanging(value);
					this.SendPropertyChanging();
					this._Longitude = value;
					this.SendPropertyChanged("Longitude");
					this.OnLongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LatLongDatumID", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public int LatLongDatumID
		{
			get
			{
				return this._LatLongDatumID;
			}
			set
			{
				if ((this._LatLongDatumID != value))
				{
					this.OnLatLongDatumIDChanging(value);
					this.SendPropertyChanging();
					this._LatLongDatumID = value;
					this.SendPropertyChanged("LatLongDatumID");
					this.OnLatLongDatumIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Elevation_m", DbType="Float")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<double> Elevation_m
		{
			get
			{
				return this._Elevation_m;
			}
			set
			{
				if ((this._Elevation_m != value))
				{
					this.OnElevation_mChanging(value);
					this.SendPropertyChanging();
					this._Elevation_m = value;
					this.SendPropertyChanged("Elevation_m");
					this.OnElevation_mChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerticalDatum", DbType="NVarChar(255)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string VerticalDatum
		{
			get
			{
				return this._VerticalDatum;
			}
			set
			{
				if ((this._VerticalDatum != value))
				{
					this.OnVerticalDatumChanging(value);
					this.SendPropertyChanging();
					this._VerticalDatum = value;
					this.SendPropertyChanged("VerticalDatum");
					this.OnVerticalDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocalX", DbType="Float")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public System.Nullable<double> LocalX
		{
			get
			{
				return this._LocalX;
			}
			set
			{
				if ((this._LocalX != value))
				{
					this.OnLocalXChanging(value);
					this.SendPropertyChanging();
					this._LocalX = value;
					this.SendPropertyChanged("LocalX");
					this.OnLocalXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocalY", DbType="Float")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public System.Nullable<double> LocalY
		{
			get
			{
				return this._LocalY;
			}
			set
			{
				if ((this._LocalY != value))
				{
					this.OnLocalYChanging(value);
					this.SendPropertyChanging();
					this._LocalY = value;
					this.SendPropertyChanged("LocalY");
					this.OnLocalYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocalProjectionID", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public System.Nullable<int> LocalProjectionID
		{
			get
			{
				return this._LocalProjectionID;
			}
			set
			{
				if ((this._LocalProjectionID != value))
				{
					this.OnLocalProjectionIDChanging(value);
					this.SendPropertyChanging();
					this._LocalProjectionID = value;
					this.SendPropertyChanged("LocalProjectionID");
					this.OnLocalProjectionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PosAccuracy_m", DbType="Float")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public System.Nullable<double> PosAccuracy_m
		{
			get
			{
				return this._PosAccuracy_m;
			}
			set
			{
				if ((this._PosAccuracy_m != value))
				{
					this.OnPosAccuracy_mChanging(value);
					this.SendPropertyChanging();
					this._PosAccuracy_m = value;
					this.SendPropertyChanged("PosAccuracy_m");
					this.OnPosAccuracy_mChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(255)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_County", DbType="NVarChar(255)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public string County
		{
			get
			{
				return this._County;
			}
			set
			{
				if ((this._County != value))
				{
					this.OnCountyChanging(value);
					this.SendPropertyChanging();
					this._County = value;
					this.SendPropertyChanged("County");
					this.OnCountyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="NVarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this.OnCommentsChanging(value);
					this.SendPropertyChanging();
					this._Comments = value;
					this.SendPropertyChanged("Comments");
					this.OnCommentsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
}
#pragma warning restore 1591
