//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterOneFlow.odws.v1_1.wcf {
    
    
    public partial class WaterML_1_1 {
        
        /// <summary>
        /// wml11url control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GenericWebservice.UserControls.TestRestUrl wml11url;
    }
}
