//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace HisCentralWSMethodTests.hiscentral.webreference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="hiscentralSoap", Namespace="http://hiscentral.cuahsi.org/20100205/")]
    public partial class hiscentral : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetSitesInBox2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSitesInBoxOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMappedVariables2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMappedVariablesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServicesInBoxOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServicesInBox2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWaterOneFlowServiceInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSeriesCatalogForBoxOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSeriesCatalogForBox2OperationCompleted;
        
        private System.Threading.SendOrPostCallback getSeriesCatalogInBoxPagedOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSearchablePathsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSearchableConceptsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOntologyTreeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWordListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public hiscentral() {
            this.Url = global::HisCentralWSMethodTests.Properties.Settings.Default.HisCentralWSMethodTests_hiscentral_webreference_hiscentral;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetSitesInBox2CompletedEventHandler GetSitesInBox2Completed;
        
        /// <remarks/>
        public event GetSitesInBoxCompletedEventHandler GetSitesInBoxCompleted;
        
        /// <remarks/>
        public event GetMappedVariables2CompletedEventHandler GetMappedVariables2Completed;
        
        /// <remarks/>
        public event GetMappedVariablesCompletedEventHandler GetMappedVariablesCompleted;
        
        /// <remarks/>
        public event GetServicesInBoxCompletedEventHandler GetServicesInBoxCompleted;
        
        /// <remarks/>
        public event GetServicesInBox2CompletedEventHandler GetServicesInBox2Completed;
        
        /// <remarks/>
        public event GetWaterOneFlowServiceInfoCompletedEventHandler GetWaterOneFlowServiceInfoCompleted;
        
        /// <remarks/>
        public event GetSeriesCatalogForBoxCompletedEventHandler GetSeriesCatalogForBoxCompleted;
        
        /// <remarks/>
        public event GetSeriesCatalogForBox2CompletedEventHandler GetSeriesCatalogForBox2Completed;
        
        /// <remarks/>
        public event getSeriesCatalogInBoxPagedCompletedEventHandler getSeriesCatalogInBoxPagedCompleted;
        
        /// <remarks/>
        public event getSearchablePathsCompletedEventHandler getSearchablePathsCompleted;
        
        /// <remarks/>
        public event GetSearchableConceptsCompletedEventHandler GetSearchableConceptsCompleted;
        
        /// <remarks/>
        public event getOntologyTreeCompletedEventHandler getOntologyTreeCompleted;
        
        /// <remarks/>
        public event GetWordListCompletedEventHandler GetWordListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hiscentral.cuahsi.org/20100205/GetSitesInBox2", RequestNamespace="http://hiscentral.cuahsi.org/20100205/", ResponseNamespace="http://hiscentral.cuahsi.org/20100205/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Site[] GetSitesInBox2(double xmin, double xmax, double ymin, double ymax, string conceptKeyword, string networkIDs) {
            object[] results = this.Invoke("GetSitesInBox2", new object[] {
                        xmin,
                        xmax,
                        ymin,
                        ymax,
                        conceptKeyword,
                        networkIDs});
            return ((Site[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSitesInBox2Async(double xmin, double xmax, double ymin, double ymax, string conceptKeyword, string networkIDs) {
            this.GetSitesInBox2Async(xmin, xmax, ymin, ymax, conceptKeyword, networkIDs, null);
        }
        
        /// <remarks/>
        public void GetSitesInBox2Async(double xmin, double xmax, double ymin, double ymax, string conceptKeyword, string networkIDs, object userState) {
            if ((this.GetSitesInBox2OperationCompleted == null)) {
                this.GetSitesInBox2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSitesInBox2OperationCompleted);
            }
            this.InvokeAsync("GetSitesInBox2", new object[] {
                        xmin,
                        xmax,
                        ymin,
                        ymax,
                        conceptKeyword,
                        networkIDs}, this.GetSitesInBox2OperationCompleted, userState);
        }
        
        private void OnGetSitesInBox2OperationCompleted(object arg) {
            if ((this.GetSitesInBox2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSitesInBox2Completed(this, new GetSitesInBox2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hiscentral.cuahsi.org/20100205/GetSitesInBox", RequestNamespace="http://hiscentral.cuahsi.org/20100205/", ResponseNamespace="http://hiscentral.cuahsi.org/20100205/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Site[] GetSitesInBox(Box box, string conceptKeyword, int[] networkIDs) {
            object[] results = this.Invoke("GetSitesInBox", new object[] {
                        box,
                        conceptKeyword,
                        networkIDs});
            return ((Site[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSitesInBoxAsync(Box box, string conceptKeyword, int[] networkIDs) {
            this.GetSitesInBoxAsync(box, conceptKeyword, networkIDs, null);
        }
        
        /// <remarks/>
        public void GetSitesInBoxAsync(Box box, string conceptKeyword, int[] networkIDs, object userState) {
            if ((this.GetSitesInBoxOperationCompleted == null)) {
                this.GetSitesInBoxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSitesInBoxOperationCompleted);
            }
            this.InvokeAsync("GetSitesInBox", new object[] {
                        box,
                        conceptKeyword,
                        networkIDs}, this.GetSitesInBoxOperationCompleted, userState);
        }
        
        private void OnGetSitesInBoxOperationCompleted(object arg) {
            if ((this.GetSitesInBoxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSitesInBoxCompleted(this, new GetSitesInBoxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hiscentral.cuahsi.org/20100205/GetMappedVariables2", RequestNamespace="http://hiscentral.cuahsi.org/20100205/", ResponseNamespace="http://hiscentral.cuahsi.org/20100205/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MappedVariable[] GetMappedVariables2(string conceptids, string Networkids) {
            object[] results = this.Invoke("GetMappedVariables2", new object[] {
                        conceptids,
                        Networkids});
            return ((MappedVariable[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMappedVariables2Async(string conceptids, string Networkids) {
            this.GetMappedVariables2Async(conceptids, Networkids, null);
        }
        
        /// <remarks/>
        public void GetMappedVariables2Async(string conceptids, string Networkids, object userState) {
            if ((this.GetMappedVariables2OperationCompleted == null)) {
                this.GetMappedVariables2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMappedVariables2OperationCompleted);
            }
            this.InvokeAsync("GetMappedVariables2", new object[] {
                        conceptids,
                        Networkids}, this.GetMappedVariables2OperationCompleted, userState);
        }
        
        private void OnGetMappedVariables2OperationCompleted(object arg) {
            if ((this.GetMappedVariables2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMappedVariables2Completed(this, new GetMappedVariables2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hiscentral.cuahsi.org/20100205/GetMappedVariables", RequestNamespace="http://hiscentral.cuahsi.org/20100205/", ResponseNamespace="http://hiscentral.cuahsi.org/20100205/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MappedVariable[] GetMappedVariables(string[] conceptids, string[] Networkids) {
            object[] results = this.Invoke("GetMappedVariables", new object[] {
                        conceptids,
                        Networkids});
            return ((MappedVariable[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMappedVariablesAsync(string[] conceptids, string[] Networkids) {
            this.GetMappedVariablesAsync(conceptids, Networkids, null);
        }
        
        /// <remarks/>
        public void GetMappedVariablesAsync(string[] conceptids, string[] Networkids, object userState) {
            if ((this.GetMappedVariablesOperationCompleted == null)) {
                this.GetMappedVariablesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMappedVariablesOperationCompleted);
            }
            this.InvokeAsync("GetMappedVariables", new object[] {
                        conceptids,
                        Networkids}, this.GetMappedVariablesOperationCompleted, userState);
        }
        
        private void OnGetMappedVariablesOperationCompleted(object arg) {
            if ((this.GetMappedVariablesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMappedVariablesCompleted(this, new GetMappedVariablesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hiscentral.cuahsi.org/20100205/GetServicesInBox", RequestNamespace="http://hiscentral.cuahsi.org/20100205/", ResponseNamespace="http://hiscentral.cuahsi.org/20100205/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceInfo[] GetServicesInBox(Box box) {
            object[] results = this.Invoke("GetServicesInBox", new object[] {
                        box});
            return ((ServiceInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetServicesInBoxAsync(Box box) {
            this.GetServicesInBoxAsync(box, null);
        }
        
        /// <remarks/>
        public void GetServicesInBoxAsync(Box box, object userState) {
            if ((this.GetServicesInBoxOperationCompleted == null)) {
                this.GetServicesInBoxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServicesInBoxOperationCompleted);
            }
            this.InvokeAsync("GetServicesInBox", new object[] {
                        box}, this.GetServicesInBoxOperationCompleted, userState);
        }
        
        private void OnGetServicesInBoxOperationCompleted(object arg) {
            if ((this.GetServicesInBoxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServicesInBoxCompleted(this, new GetServicesInBoxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hiscentral.cuahsi.org/20100205/GetServicesInBox2", RequestNamespace="http://hiscentral.cuahsi.org/20100205/", ResponseNamespace="http://hiscentral.cuahsi.org/20100205/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceInfo[] GetServicesInBox2(double xmin, double ymin, double xmax, double ymax) {
            object[] results = this.Invoke("GetServicesInBox2", new object[] {
                        xmin,
                        ymin,
                        xmax,
                        ymax});
            return ((ServiceInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetServicesInBox2Async(double xmin, double ymin, double xmax, double ymax) {
            this.GetServicesInBox2Async(xmin, ymin, xmax, ymax, null);
        }
        
        /// <remarks/>
        public void GetServicesInBox2Async(double xmin, double ymin, double xmax, double ymax, object userState) {
            if ((this.GetServicesInBox2OperationCompleted == null)) {
                this.GetServicesInBox2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServicesInBox2OperationCompleted);
            }
            this.InvokeAsync("GetServicesInBox2", new object[] {
                        xmin,
                        ymin,
                        xmax,
                        ymax}, this.GetServicesInBox2OperationCompleted, userState);
        }
        
        private void OnGetServicesInBox2OperationCompleted(object arg) {
            if ((this.GetServicesInBox2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServicesInBox2Completed(this, new GetServicesInBox2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hiscentral.cuahsi.org/20100205/GetWaterOneFlowServiceInfo", RequestNamespace="http://hiscentral.cuahsi.org/20100205/", ResponseNamespace="http://hiscentral.cuahsi.org/20100205/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceInfo[] GetWaterOneFlowServiceInfo() {
            object[] results = this.Invoke("GetWaterOneFlowServiceInfo", new object[0]);
            return ((ServiceInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetWaterOneFlowServiceInfoAsync() {
            this.GetWaterOneFlowServiceInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetWaterOneFlowServiceInfoAsync(object userState) {
            if ((this.GetWaterOneFlowServiceInfoOperationCompleted == null)) {
                this.GetWaterOneFlowServiceInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWaterOneFlowServiceInfoOperationCompleted);
            }
            this.InvokeAsync("GetWaterOneFlowServiceInfo", new object[0], this.GetWaterOneFlowServiceInfoOperationCompleted, userState);
        }
        
        private void OnGetWaterOneFlowServiceInfoOperationCompleted(object arg) {
            if ((this.GetWaterOneFlowServiceInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWaterOneFlowServiceInfoCompleted(this, new GetWaterOneFlowServiceInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hiscentral.cuahsi.org/20100205/GetSeriesCatalogForBox", RequestNamespace="http://hiscentral.cuahsi.org/20100205/", ResponseNamespace="http://hiscentral.cuahsi.org/20100205/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SeriesRecord[] GetSeriesCatalogForBox(Box box, string conceptCode, int[] networkIDs, string beginDate, string endDate) {
            object[] results = this.Invoke("GetSeriesCatalogForBox", new object[] {
                        box,
                        conceptCode,
                        networkIDs,
                        beginDate,
                        endDate});
            return ((SeriesRecord[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSeriesCatalogForBoxAsync(Box box, string conceptCode, int[] networkIDs, string beginDate, string endDate) {
            this.GetSeriesCatalogForBoxAsync(box, conceptCode, networkIDs, beginDate, endDate, null);
        }
        
        /// <remarks/>
        public void GetSeriesCatalogForBoxAsync(Box box, string conceptCode, int[] networkIDs, string beginDate, string endDate, object userState) {
            if ((this.GetSeriesCatalogForBoxOperationCompleted == null)) {
                this.GetSeriesCatalogForBoxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSeriesCatalogForBoxOperationCompleted);
            }
            this.InvokeAsync("GetSeriesCatalogForBox", new object[] {
                        box,
                        conceptCode,
                        networkIDs,
                        beginDate,
                        endDate}, this.GetSeriesCatalogForBoxOperationCompleted, userState);
        }
        
        private void OnGetSeriesCatalogForBoxOperationCompleted(object arg) {
            if ((this.GetSeriesCatalogForBoxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSeriesCatalogForBoxCompleted(this, new GetSeriesCatalogForBoxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hiscentral.cuahsi.org/20100205/GetSeriesCatalogForBox2", RequestNamespace="http://hiscentral.cuahsi.org/20100205/", ResponseNamespace="http://hiscentral.cuahsi.org/20100205/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SeriesRecord[] GetSeriesCatalogForBox2(double xmin, double xmax, double ymin, double ymax, string conceptKeyword, string networkIDs, string beginDate, string endDate) {
            object[] results = this.Invoke("GetSeriesCatalogForBox2", new object[] {
                        xmin,
                        xmax,
                        ymin,
                        ymax,
                        conceptKeyword,
                        networkIDs,
                        beginDate,
                        endDate});
            return ((SeriesRecord[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSeriesCatalogForBox2Async(double xmin, double xmax, double ymin, double ymax, string conceptKeyword, string networkIDs, string beginDate, string endDate) {
            this.GetSeriesCatalogForBox2Async(xmin, xmax, ymin, ymax, conceptKeyword, networkIDs, beginDate, endDate, null);
        }
        
        /// <remarks/>
        public void GetSeriesCatalogForBox2Async(double xmin, double xmax, double ymin, double ymax, string conceptKeyword, string networkIDs, string beginDate, string endDate, object userState) {
            if ((this.GetSeriesCatalogForBox2OperationCompleted == null)) {
                this.GetSeriesCatalogForBox2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSeriesCatalogForBox2OperationCompleted);
            }
            this.InvokeAsync("GetSeriesCatalogForBox2", new object[] {
                        xmin,
                        xmax,
                        ymin,
                        ymax,
                        conceptKeyword,
                        networkIDs,
                        beginDate,
                        endDate}, this.GetSeriesCatalogForBox2OperationCompleted, userState);
        }
        
        private void OnGetSeriesCatalogForBox2OperationCompleted(object arg) {
            if ((this.GetSeriesCatalogForBox2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSeriesCatalogForBox2Completed(this, new GetSeriesCatalogForBox2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hiscentral.cuahsi.org/20100205/getSeriesCatalogInBoxPaged", RequestNamespace="http://hiscentral.cuahsi.org/20100205/", ResponseNamespace="http://hiscentral.cuahsi.org/20100205/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SeriesRecord[] getSeriesCatalogInBoxPaged(double xmin, double xmax, double ymin, double ymax, string conceptKeyword, string networkIDs, string beginDate, string endDate, int pageno) {
            object[] results = this.Invoke("getSeriesCatalogInBoxPaged", new object[] {
                        xmin,
                        xmax,
                        ymin,
                        ymax,
                        conceptKeyword,
                        networkIDs,
                        beginDate,
                        endDate,
                        pageno});
            return ((SeriesRecord[])(results[0]));
        }
        
        /// <remarks/>
        public void getSeriesCatalogInBoxPagedAsync(double xmin, double xmax, double ymin, double ymax, string conceptKeyword, string networkIDs, string beginDate, string endDate, int pageno) {
            this.getSeriesCatalogInBoxPagedAsync(xmin, xmax, ymin, ymax, conceptKeyword, networkIDs, beginDate, endDate, pageno, null);
        }
        
        /// <remarks/>
        public void getSeriesCatalogInBoxPagedAsync(double xmin, double xmax, double ymin, double ymax, string conceptKeyword, string networkIDs, string beginDate, string endDate, int pageno, object userState) {
            if ((this.getSeriesCatalogInBoxPagedOperationCompleted == null)) {
                this.getSeriesCatalogInBoxPagedOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSeriesCatalogInBoxPagedOperationCompleted);
            }
            this.InvokeAsync("getSeriesCatalogInBoxPaged", new object[] {
                        xmin,
                        xmax,
                        ymin,
                        ymax,
                        conceptKeyword,
                        networkIDs,
                        beginDate,
                        endDate,
                        pageno}, this.getSeriesCatalogInBoxPagedOperationCompleted, userState);
        }
        
        private void OngetSeriesCatalogInBoxPagedOperationCompleted(object arg) {
            if ((this.getSeriesCatalogInBoxPagedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSeriesCatalogInBoxPagedCompleted(this, new getSeriesCatalogInBoxPagedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hiscentral.cuahsi.org/20100205/getSearchablePaths", RequestNamespace="http://hiscentral.cuahsi.org/20100205/", ResponseNamespace="http://hiscentral.cuahsi.org/20100205/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public OntologyPath[] getSearchablePaths() {
            object[] results = this.Invoke("getSearchablePaths", new object[0]);
            return ((OntologyPath[])(results[0]));
        }
        
        /// <remarks/>
        public void getSearchablePathsAsync() {
            this.getSearchablePathsAsync(null);
        }
        
        /// <remarks/>
        public void getSearchablePathsAsync(object userState) {
            if ((this.getSearchablePathsOperationCompleted == null)) {
                this.getSearchablePathsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSearchablePathsOperationCompleted);
            }
            this.InvokeAsync("getSearchablePaths", new object[0], this.getSearchablePathsOperationCompleted, userState);
        }
        
        private void OngetSearchablePathsOperationCompleted(object arg) {
            if ((this.getSearchablePathsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSearchablePathsCompleted(this, new getSearchablePathsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hiscentral.cuahsi.org/20100205/GetSearchableConcepts", RequestNamespace="http://hiscentral.cuahsi.org/20100205/", ResponseNamespace="http://hiscentral.cuahsi.org/20100205/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetSearchableConcepts() {
            object[] results = this.Invoke("GetSearchableConcepts", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSearchableConceptsAsync() {
            this.GetSearchableConceptsAsync(null);
        }
        
        /// <remarks/>
        public void GetSearchableConceptsAsync(object userState) {
            if ((this.GetSearchableConceptsOperationCompleted == null)) {
                this.GetSearchableConceptsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSearchableConceptsOperationCompleted);
            }
            this.InvokeAsync("GetSearchableConcepts", new object[0], this.GetSearchableConceptsOperationCompleted, userState);
        }
        
        private void OnGetSearchableConceptsOperationCompleted(object arg) {
            if ((this.GetSearchableConceptsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSearchableConceptsCompleted(this, new GetSearchableConceptsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hiscentral.cuahsi.org/20100205/getOntologyTree", RequestNamespace="http://hiscentral.cuahsi.org/20100205/", ResponseNamespace="http://hiscentral.cuahsi.org/20100205/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OntologyNode getOntologyTree(string conceptKeyword) {
            object[] results = this.Invoke("getOntologyTree", new object[] {
                        conceptKeyword});
            return ((OntologyNode)(results[0]));
        }
        
        /// <remarks/>
        public void getOntologyTreeAsync(string conceptKeyword) {
            this.getOntologyTreeAsync(conceptKeyword, null);
        }
        
        /// <remarks/>
        public void getOntologyTreeAsync(string conceptKeyword, object userState) {
            if ((this.getOntologyTreeOperationCompleted == null)) {
                this.getOntologyTreeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOntologyTreeOperationCompleted);
            }
            this.InvokeAsync("getOntologyTree", new object[] {
                        conceptKeyword}, this.getOntologyTreeOperationCompleted, userState);
        }
        
        private void OngetOntologyTreeOperationCompleted(object arg) {
            if ((this.getOntologyTreeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOntologyTreeCompleted(this, new getOntologyTreeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hiscentral.cuahsi.org/20100205/GetWordList", RequestNamespace="http://hiscentral.cuahsi.org/20100205/", ResponseNamespace="http://hiscentral.cuahsi.org/20100205/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetWordList(string prefixText, int count) {
            object[] results = this.Invoke("GetWordList", new object[] {
                        prefixText,
                        count});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetWordListAsync(string prefixText, int count) {
            this.GetWordListAsync(prefixText, count, null);
        }
        
        /// <remarks/>
        public void GetWordListAsync(string prefixText, int count, object userState) {
            if ((this.GetWordListOperationCompleted == null)) {
                this.GetWordListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWordListOperationCompleted);
            }
            this.InvokeAsync("GetWordList", new object[] {
                        prefixText,
                        count}, this.GetWordListOperationCompleted, userState);
        }
        
        private void OnGetWordListOperationCompleted(object arg) {
            if ((this.GetWordListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWordListCompleted(this, new GetWordListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/")]
    public partial class Site {
        
        private string siteNameField;
        
        private string siteCodeField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private string hUCField;
        
        private int hUCnumericField;
        
        private string servCodeField;
        
        private string servURLField;
        
        /// <remarks/>
        public string SiteName {
            get {
                return this.siteNameField;
            }
            set {
                this.siteNameField = value;
            }
        }
        
        /// <remarks/>
        public string SiteCode {
            get {
                return this.siteCodeField;
            }
            set {
                this.siteCodeField = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public string HUC {
            get {
                return this.hUCField;
            }
            set {
                this.hUCField = value;
            }
        }
        
        /// <remarks/>
        public int HUCnumeric {
            get {
                return this.hUCnumericField;
            }
            set {
                this.hUCnumericField = value;
            }
        }
        
        /// <remarks/>
        public string servCode {
            get {
                return this.servCodeField;
            }
            set {
                this.servCodeField = value;
            }
        }
        
        /// <remarks/>
        public string servURL {
            get {
                return this.servURLField;
            }
            set {
                this.servURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/")]
    public partial class OntologyNode {
        
        private string keywordField;
        
        private int conceptidField;
        
        private OntologyNode[] childNodesField;
        
        /// <remarks/>
        public string keyword {
            get {
                return this.keywordField;
            }
            set {
                this.keywordField = value;
            }
        }
        
        /// <remarks/>
        public int conceptid {
            get {
                return this.conceptidField;
            }
            set {
                this.conceptidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public OntologyNode[] childNodes {
            get {
                return this.childNodesField;
            }
            set {
                this.childNodesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/")]
    public partial class OntologyPath {
        
        private string conceptIDField;
        
        private string searchableKeywordField;
        
        private string conceptNameField;
        
        private string conceptPathField;
        
        /// <remarks/>
        public string conceptID {
            get {
                return this.conceptIDField;
            }
            set {
                this.conceptIDField = value;
            }
        }
        
        /// <remarks/>
        public string SearchableKeyword {
            get {
                return this.searchableKeywordField;
            }
            set {
                this.searchableKeywordField = value;
            }
        }
        
        /// <remarks/>
        public string ConceptName {
            get {
                return this.conceptNameField;
            }
            set {
                this.conceptNameField = value;
            }
        }
        
        /// <remarks/>
        public string ConceptPath {
            get {
                return this.conceptPathField;
            }
            set {
                this.conceptPathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/")]
    public partial class SeriesRecord {
        
        private string servCodeField;
        
        private string servURLField;
        
        private string locationField;
        
        private string varCodeField;
        
        private string varNameField;
        
        private string beginDateField;
        
        private string endDateField;
        
        private string authtokenField;
        
        private int valueCountField;
        
        private string sitenameField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private string datatypeField;
        
        private string valuetypeField;
        
        private string samplemediumField;
        
        private string timeunitsField;
        
        private string conceptKeywordField;
        
        private string genCategoryField;
        
        private string timeSupportField;
        
        /// <remarks/>
        public string ServCode {
            get {
                return this.servCodeField;
            }
            set {
                this.servCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ServURL {
            get {
                return this.servURLField;
            }
            set {
                this.servURLField = value;
            }
        }
        
        /// <remarks/>
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string VarCode {
            get {
                return this.varCodeField;
            }
            set {
                this.varCodeField = value;
            }
        }
        
        /// <remarks/>
        public string VarName {
            get {
                return this.varNameField;
            }
            set {
                this.varNameField = value;
            }
        }
        
        /// <remarks/>
        public string beginDate {
            get {
                return this.beginDateField;
            }
            set {
                this.beginDateField = value;
            }
        }
        
        /// <remarks/>
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public string authtoken {
            get {
                return this.authtokenField;
            }
            set {
                this.authtokenField = value;
            }
        }
        
        /// <remarks/>
        public int ValueCount {
            get {
                return this.valueCountField;
            }
            set {
                this.valueCountField = value;
            }
        }
        
        /// <remarks/>
        public string Sitename {
            get {
                return this.sitenameField;
            }
            set {
                this.sitenameField = value;
            }
        }
        
        /// <remarks/>
        public double latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public double longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public string datatype {
            get {
                return this.datatypeField;
            }
            set {
                this.datatypeField = value;
            }
        }
        
        /// <remarks/>
        public string valuetype {
            get {
                return this.valuetypeField;
            }
            set {
                this.valuetypeField = value;
            }
        }
        
        /// <remarks/>
        public string samplemedium {
            get {
                return this.samplemediumField;
            }
            set {
                this.samplemediumField = value;
            }
        }
        
        /// <remarks/>
        public string timeunits {
            get {
                return this.timeunitsField;
            }
            set {
                this.timeunitsField = value;
            }
        }
        
        /// <remarks/>
        public string conceptKeyword {
            get {
                return this.conceptKeywordField;
            }
            set {
                this.conceptKeywordField = value;
            }
        }
        
        /// <remarks/>
        public string genCategory {
            get {
                return this.genCategoryField;
            }
            set {
                this.genCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string TimeSupport {
            get {
                return this.timeSupportField;
            }
            set {
                this.timeSupportField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/")]
    public partial class ServiceInfo {
        
        private string servURLField;
        
        private string titleField;
        
        private string serviceDescriptionURLField;
        
        private string nameField;
        
        private string emailField;
        
        private string phoneField;
        
        private string organizationField;
        
        private string orgwebsiteField;
        
        private string citationField;
        
        private string aabstractField;
        
        private int valuecountField;
        
        private int variablecountField;
        
        private int sitecountField;
        
        private int serviceIDField;
        
        private string networkNameField;
        
        private double minxField;
        
        private double minyField;
        
        private double maxxField;
        
        private double maxyField;
        
        private string serviceStatusField;
        
        /// <remarks/>
        public string servURL {
            get {
                return this.servURLField;
            }
            set {
                this.servURLField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceDescriptionURL {
            get {
                return this.serviceDescriptionURLField;
            }
            set {
                this.serviceDescriptionURLField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        public string orgwebsite {
            get {
                return this.orgwebsiteField;
            }
            set {
                this.orgwebsiteField = value;
            }
        }
        
        /// <remarks/>
        public string citation {
            get {
                return this.citationField;
            }
            set {
                this.citationField = value;
            }
        }
        
        /// <remarks/>
        public string aabstract {
            get {
                return this.aabstractField;
            }
            set {
                this.aabstractField = value;
            }
        }
        
        /// <remarks/>
        public int valuecount {
            get {
                return this.valuecountField;
            }
            set {
                this.valuecountField = value;
            }
        }
        
        /// <remarks/>
        public int variablecount {
            get {
                return this.variablecountField;
            }
            set {
                this.variablecountField = value;
            }
        }
        
        /// <remarks/>
        public int sitecount {
            get {
                return this.sitecountField;
            }
            set {
                this.sitecountField = value;
            }
        }
        
        /// <remarks/>
        public int ServiceID {
            get {
                return this.serviceIDField;
            }
            set {
                this.serviceIDField = value;
            }
        }
        
        /// <remarks/>
        public string NetworkName {
            get {
                return this.networkNameField;
            }
            set {
                this.networkNameField = value;
            }
        }
        
        /// <remarks/>
        public double minx {
            get {
                return this.minxField;
            }
            set {
                this.minxField = value;
            }
        }
        
        /// <remarks/>
        public double miny {
            get {
                return this.minyField;
            }
            set {
                this.minyField = value;
            }
        }
        
        /// <remarks/>
        public double maxx {
            get {
                return this.maxxField;
            }
            set {
                this.maxxField = value;
            }
        }
        
        /// <remarks/>
        public double maxy {
            get {
                return this.maxyField;
            }
            set {
                this.maxyField = value;
            }
        }
        
        /// <remarks/>
        public string serviceStatus {
            get {
                return this.serviceStatusField;
            }
            set {
                this.serviceStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/")]
    public partial class MappedVariable {
        
        private string variableNameField;
        
        private string variableCodeField;
        
        private string servCodeField;
        
        private string wSDLField;
        
        private string conceptKeywordField;
        
        private string conceptCodeField;
        
        /// <remarks/>
        public string variableName {
            get {
                return this.variableNameField;
            }
            set {
                this.variableNameField = value;
            }
        }
        
        /// <remarks/>
        public string variableCode {
            get {
                return this.variableCodeField;
            }
            set {
                this.variableCodeField = value;
            }
        }
        
        /// <remarks/>
        public string servCode {
            get {
                return this.servCodeField;
            }
            set {
                this.servCodeField = value;
            }
        }
        
        /// <remarks/>
        public string WSDL {
            get {
                return this.wSDLField;
            }
            set {
                this.wSDLField = value;
            }
        }
        
        /// <remarks/>
        public string conceptKeyword {
            get {
                return this.conceptKeywordField;
            }
            set {
                this.conceptKeywordField = value;
            }
        }
        
        /// <remarks/>
        public string conceptCode {
            get {
                return this.conceptCodeField;
            }
            set {
                this.conceptCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hiscentral.cuahsi.org/20100205/")]
    public partial class Box {
        
        private double xminField;
        
        private double xmaxField;
        
        private double yminField;
        
        private double ymaxField;
        
        /// <remarks/>
        public double xmin {
            get {
                return this.xminField;
            }
            set {
                this.xminField = value;
            }
        }
        
        /// <remarks/>
        public double xmax {
            get {
                return this.xmaxField;
            }
            set {
                this.xmaxField = value;
            }
        }
        
        /// <remarks/>
        public double ymin {
            get {
                return this.yminField;
            }
            set {
                this.yminField = value;
            }
        }
        
        /// <remarks/>
        public double ymax {
            get {
                return this.ymaxField;
            }
            set {
                this.ymaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetSitesInBox2CompletedEventHandler(object sender, GetSitesInBox2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSitesInBox2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSitesInBox2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Site[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Site[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetSitesInBoxCompletedEventHandler(object sender, GetSitesInBoxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSitesInBoxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSitesInBoxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Site[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Site[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMappedVariables2CompletedEventHandler(object sender, GetMappedVariables2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMappedVariables2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMappedVariables2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MappedVariable[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MappedVariable[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMappedVariablesCompletedEventHandler(object sender, GetMappedVariablesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMappedVariablesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMappedVariablesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MappedVariable[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MappedVariable[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetServicesInBoxCompletedEventHandler(object sender, GetServicesInBoxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServicesInBoxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServicesInBoxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetServicesInBox2CompletedEventHandler(object sender, GetServicesInBox2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServicesInBox2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServicesInBox2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetWaterOneFlowServiceInfoCompletedEventHandler(object sender, GetWaterOneFlowServiceInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWaterOneFlowServiceInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWaterOneFlowServiceInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetSeriesCatalogForBoxCompletedEventHandler(object sender, GetSeriesCatalogForBoxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSeriesCatalogForBoxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSeriesCatalogForBoxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SeriesRecord[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SeriesRecord[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetSeriesCatalogForBox2CompletedEventHandler(object sender, GetSeriesCatalogForBox2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSeriesCatalogForBox2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSeriesCatalogForBox2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SeriesRecord[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SeriesRecord[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getSeriesCatalogInBoxPagedCompletedEventHandler(object sender, getSeriesCatalogInBoxPagedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSeriesCatalogInBoxPagedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSeriesCatalogInBoxPagedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SeriesRecord[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SeriesRecord[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getSearchablePathsCompletedEventHandler(object sender, getSearchablePathsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSearchablePathsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSearchablePathsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OntologyPath[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OntologyPath[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetSearchableConceptsCompletedEventHandler(object sender, GetSearchableConceptsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSearchableConceptsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSearchableConceptsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getOntologyTreeCompletedEventHandler(object sender, getOntologyTreeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOntologyTreeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOntologyTreeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OntologyNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OntologyNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetWordListCompletedEventHandler(object sender, GetWordListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWordListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWordListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591